sudo: required

language: ruby

services:
  - docker

install:
  - docker build -t hunterlong/auto-phusion-rails .
  - docker run -d -p 127.0.0.1:80:80 -e 'GIT_PERSONAL_TOKEN=$GIT_PERSONAL_TOKEN' -e 'GIT_EMAIL=$GIT_EMAIL' -e 'GIT_USERNAME=$GIT_USERNAME' -e 'GIT_BRANCH=$GIT_BRANCH' -e 'GIT_REPO=$GIT_REPO' hunterlong/auto-phusion-rails

script:
  - docker ps -a
